{% set name = "rioxarray" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0fa9b21a048c34cc67eecc4e56a5286245620f62684967394847c2957d7061c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - rasterio >=1.1.1
    - scipy
    - xarray >=0.17
    - pyproj >=2.2
    - packaging
test:
  imports:
    - rioxarray

about:
  home: http://github.com/corteva/rioxarray
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: rasterio xarray extension.
  description: rasterio xarray extension.
  doc_url: https://corteva.github.io/rioxarray
  dev_url: http://github.com/corteva/rioxarray

extra:
  recipe-maintainers:
    - snowman2
