{% set name = "rioxarray" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 303e39c30918899ceeb601db628273a55796268e9e4e8b78b836080586c350e7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - rasterio
    - scipy
    - xarray >=0.17
    - pyproj >=2.2
    - packaging
test:
  imports:
    - rioxarray

about:
  home: http://github.com/corteva/rioxarray
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: rasterio xarray extension.
  description: rasterio xarray extension.
  doc_url: https://corteva.github.io/rioxarray
  dev_url: http://github.com/corteva/rioxarray

extra:
  recipe-maintainers:
    - snowman2
