{% set python_min = "3.10" %}
{% set name = "rioxarray" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7819a0036fd874c8c8e280447cbbe43d8dc72fc4a14ac7852a665b1bdb7d4b04

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - rasterio >=1.3.7
    - scipy
    - xarray >=2024.7.0
    - pyproj >=3.3
    - packaging
    - numpy >=1.23
test:
  requires:
    - python {{ python_min }}
  imports:
    - rioxarray

about:
  home: http://github.com/corteva/rioxarray
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: rasterio xarray extension.
  description: rasterio xarray extension.
  doc_url: https://corteva.github.io/rioxarray
  dev_url: http://github.com/corteva/rioxarray

extra:
  recipe-maintainers:
    - snowman2
